// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1721:Property names should not match get methods", Justification = "<Pending>", Scope = "member", Target = "~P:Hille.Aras.DevTool.Common.Commands.Command.ArasCommands.ArasBaseCommand.Name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA3075:Insecure DTD processing in XML", Justification = "<Pending>", Scope = "member", Target = "~M:Hille.Aras.DevTool.Common.Commands.Command.ManifestParser.LoadFileList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA3075:Insecure DTD processing in XML", Justification = "<Pending>", Scope = "member", Target = "~M:Hille.Aras.DevTool.Common.Commands.Command.AMLFile.LoadAmls")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA3075:Insecure DTD processing in XML", Justification = "<Pending>", Scope = "member", Target = "~M:Hille.Aras.DevTool.Common.Configuration.ArasXmlStoredConfig.#ctor(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA3075:Insecure DTD processing in XML", Justification = "<Pending>", Scope = "member", Target = "~M:Hille.Aras.DevTool.Common.Configuration.ArasXmlStoredConfig.Setup(System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Hille.Aras.DevTool.Common.Configuration.ArasXmlStoredConfig.Setup(System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA3075:Insecure DTD processing in XML", Justification = "<Pending>", Scope = "member", Target = "~M:Hille.Aras.DevTool.Common.Commands.DefaultSetupHandler.GetNewEnvironmentNode(System.String)~System.Xml.XmlNode")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA3075:Insecure DTD processing in XML", Justification = "<Pending>", Scope = "member", Target = "~M:Hille.Aras.DevTool.Common.Commands.DefaultSetupHandler.SetupConnection(System.String)~Hille.Aras.DevTool.Interfaces.Configuration.IArasConnectionConfig")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Hille.Aras.DevTool.Common.Commands.DefaultSetupHandler.SetupConnection(System.String)~Hille.Aras.DevTool.Interfaces.Configuration.IArasConnectionConfig")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA3075:Insecure DTD processing in XML", Justification = "<Pending>", Scope = "member", Target = "~M:Hille.Aras.DevTool.Common.Commands.DefaultSetupHandler.GetArasConnectionConfig(System.String)~Hille.Aras.DevTool.Interfaces.Configuration.IArasConnectionConfig")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA3075:Insecure DTD processing in XML", Justification = "<Pending>", Scope = "member", Target = "~M:Hille.Aras.DevTool.Common.Commands.DefaultSetupHandler.AddNewEnvNode(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Hille.Aras.DevTool.Common.Commands.DefaultSetupHandler.GetDefaultDBName(Hille.Aras.DevTool.Interfaces.Configuration.IArasConnectionConfig,System.String)~System.String")]
